Feature/tests
SamuelSsc/Onboarding-Instituto-Back pull request #13
Opened 2022-09-13 15:21 UTC by SamuelSsc

- Criado arquivos .env
 - Criado test de hello word

2022-09-14 13:03 UTC, dan-ueno requested changes

2022-09-14 13:03 UTC, dan-ueno commented on .gitignore
> +.env
nas issues falava de env? é bacana mas sei la se precisa pro onboard hahaha

2022-09-14 13:03 UTC, dan-ueno commented on src/setup.ts
> +  const app = new ApolloServer({ typeDefs, resolvers });
ja q vc separou o setup, ficaria legal separar o typedef e resolver em outros dois arquivos tbm, assim sempre que vc for adicionar coisa vc nao muda o setup

2022-09-14 13:03 UTC, dan-ueno commented on src/test/hello.test.ts
> +  const EXPECTED_RESPONSE = { data: { hello: "Hello Word!" } };
aqui nao precisa deixar em snake/caps
outro ponto, essa seria a resposta esperada do it, então melhor declarar dentro dele

2022-09-14 13:03 UTC, dan-ueno commented on src/test/hello.test.ts
> +  it("should return hello word", async () => {
aqui dentro do it, a gente coloca o teste e tenta seguir um padrão chamado AAA
Arrange - ajusta o que precisar (cria seed do banco, input da query/mutation, etc)
Action - ação: coisas que vc precisa fazer (chamada da query/mutation, criar expect response, buscar valor atualizado no banco, etc)
Assert - verificações/expects

2022-09-14 13:03 UTC, dan-ueno commented on src/test/hello.test.ts
> +    const query = `
a query em si vai ser a mesma para todos os testes (its), entao ela deveria estar logo abaixo do describe

2022-09-14 13:03 UTC, dan-ueno commented on src/test/hello.test.ts
> +    console.log(response.data);
👀

2022-09-14 13:03 UTC, dan-ueno commented on src/test/hello.test.ts
> +    expect(response.data).to.be.deep.eq(EXPECTED_RESPONSE);
deep equal é mto bom usar, boa 🎉

2022-09-14 13:24 UTC, SamuelSsc commented on src/test/hello.test.ts
> +    expect(response.data).to.be.deep.eq(EXPECTED_RESPONSE);
Vlw

2022-09-14 13:45 UTC, SamuelSsc commented on .gitignore
> +.env
falava pra usar para direcionar certinho a questão dos 2 bancos, para quando rodar o teste ir pro banco de teste e quando dar start ir pro local.

2022-09-15 15:34 UTC, dan-ueno requested changes

2022-09-15 15:34 UTC, dan-ueno commented on src/data-source.ts
> +export let AppDataSource: DataSource;
aqui ficou esquisito. Eu deixaria em const, ai dentro do createConnection daria um appdatasource.initialize

2022-09-15 15:34 UTC, dan-ueno commented on src/schema/resolvers.ts
> -const dataSource = createConnection();
e aqui daria pra manter, chama o appdatasource.manager

2022-09-15 15:34 UTC, dan-ueno commented on src/setup.ts
> +  await AppDataSource.initialize();
e aqui seria so o await createConnection

2022-09-16 13:37 UTC, dan-ueno approved these changes

2022-09-16 13:37 UTC, dan-ueno commented on src/schema/resolvers.ts
> +      const VALIDATOR_PASSWORD = /^((?=\S*?[a-z,A-Z])(?=\S*?[0-9]).{6,})\S/;
acho que o nome pode ser regex msm kkkk

2022-09-16 13:37 UTC, dan-ueno commented on src/schema/resolvers.ts
> +      user.name = args.data.name;
agora que vc conseguiu salvar usando entidade.parametro, da uma olhada em `Object.assign`

2022-09-16 13:37 UTC, dan-ueno commented on src/test/hello.test.ts
> +    const urlDB = "http://localhost:4000//graphql";
a url fica junto do describe, afinal em todo o teste vc vai usar o mesmo post. O que fica dentro do it é coisa que é apenas dele.

2022-09-16 15:06 UTC, SamuelSsc commented on src/schema/resolvers.ts
> +      user.name = args.data.name;
Beleza, vou dar uma estudada sim!

2022-09-16 15:22 UTC, merged